// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package license

import (
	"gf-admin/api/license"
	logic "gf-admin/internal/logic/license"
)

type ControllerV1 struct {
	// 注入logic服务
	license *logic.License
}

func NewV1() license.ILicenseV1 {
	return &ControllerV1{
		logic.New(),
	}
}
