// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package device_user

import (
	"gf-admin/internal/logic/device_user"
)

type ControllerV1 struct {
	//注入逻辑层
	deviceUser *device_user.DeviceUser
}

func NewV1() *ControllerV1 {
	return &ControllerV1{
		deviceUser: device_user.New(),
	}
}
