// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package login

import (
	loginApi "gf-admin/api/login"
	loginLogic "gf-admin/internal/logic/login"
)

type ControllerV1 struct {
	//注入login逻辑层
	login *loginLogic.Login
}

func NewV1() loginApi.ILoginV1 {
	return &ControllerV1{
		login: loginLogic.New(),
	}
}
