// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package device_menu

import (
	api "gf-admin/api/device_menu"
	logic "gf-admin/internal/logic/device_menu"
)

type ControllerV1 struct {
	deviceMenu *logic.DeviceMenu
}

func NewV1() api.IDeviceMenuV1 {
	return &ControllerV1{
		deviceMenu: logic.New(),
	}
}
