// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gf-admin/internal/dao/internal"
)

// deviceUserDao is the data access object for the table device_user.
// You can define custom methods on it to extend its functionality as needed.
type deviceUserDao struct {
	*internal.DeviceUserDao
}

var (
	// DeviceUser is a globally accessible object for table device_user operations.
	DeviceUser = deviceUserDao{internal.NewDeviceUserDao()}
)

// Add your custom methods and functionality below.
