// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gf-admin/internal/dao/internal"
)

// deviceRoleDao is the data access object for the table device_role.
// You can define custom methods on it to extend its functionality as needed.
type deviceRoleDao struct {
	*internal.DeviceRoleDao
}

var (
	// DeviceRole is a globally accessible object for table device_role operations.
	DeviceRole = deviceRoleDao{internal.NewDeviceRoleDao()}
)

// Add your custom methods and functionality below.
