// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gf-admin/internal/dao/internal"
)

// licenseDao is the data access object for the table license.
// You can define custom methods on it to extend its functionality as needed.
type licenseDao struct {
	*internal.LicenseDao
}

var (
	// License is a globally accessible object for table license operations.
	License = licenseDao{internal.NewLicenseDao()}
)

// Add your custom methods and functionality below.
